run:
  mode: 'Test'
  device: 'gpu'


transforms: none

dataset:
  class_name: "ISIC2020Dataset"
  training:
    params:
      root_dir: "/content/ISIC2018"
      x_folder: "ISIC2018_Task1-2_Training_Input"
      y_folder: "ISIC2018_Task1_Training_GroundTruth"
      x_filename_format: "ISIC_*.jpg"
      y_filename_format: "ISIC_*_segmentation.png"
      transform_list:
        - Rescale(256)
      
  validation:
    params:
      root_dir: "/content/ISIC2018"
      x_folder: "ISIC2018_Task1-2_Validation_Input"
      y_folder: "ISIC2018_Task1_Validation_GroundTruth"
      x_filename_format: "ISIC_*.jpg"
      y_filename_format: "ISIC_*_segmentation.png"
      transform_list:
        - Rescale(256)
      
  test:
    params:
      root_dir: "/content/ISIC2018"
      x_folder: "ISIC2018_Task1-2_Test_Input"
      x_filename_format: "ISIC_*.jpg"
      transform_list:
        - Rescale(256)
      

  number_classes: 2

data_loader:
  train: 
    batch_size: 1
    shuffle: true
    # num_workers: 1
  
  validation: 
    batch_size: 1
    shuffle: false
    # num_workers: 1

  test:
    batch_size: 1
    shuffle: false
    # num_workers: 1

training:
  lr: 0.002
  patience: 5
  epochs: 50
  progress_p: 

model:
  save_path: './saved_models/s'
  name: 'UNET'
  params:
    in_channels: 4
    out_channels: 2

# preprocess:
